orgname: CWG
servicenow_req: REQ0a012345

app: billing-api
env: dev

displayname: "Billing APP2 (Dev)"
apptype: regular_web

granttypes:
  - authorization_code
  - refresh_token

callbacks:
  - https://billing-dev.example.com/callback

logouturls:
  - https://billing-dev.example.com/logout

allowedorigins:
  - https://billing-dev.example.com

clientmetadata:
  system: billing
  owner_team: billing-platform
  environment: dev

jwtlifetimeinseconds: 3600
